# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.CharField(default='', max_length=256),
        ),
    ]
