# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='group',
            new_name='email',
        ),
    ]
