# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'blog_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docfile', models.ImageField(upload_to='image/')),
                ('title', models.CharField(default='', max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('subtitle', models.CharField(default='', max_length=256)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='home.Category')),
            ],
            options={
                'db_table': 'blog_document',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'blog_tags',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firt_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'blog_users',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tags',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Users'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(related_name='tags_ids', to='home.Tags'),
        ),
        migrations.AddField(
            model_name='document',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_id', to='home.Users'),
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Users'),
        ),
    ]
