# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('users', models.ManyToManyField(related_name='users_ids', to='home.Users')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'blog_group',
            },
        ),
    ]
