# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
