# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
