# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160114_0124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
        migrations.AlterModelTable(
            name='document',
            table='blog_document',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='blog_tags',
        ),
        migrations.AlterModelTable(
            name='users',
            table='blog_users',
        ),
    ]
