# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20151225_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='model_pic',
            new_name='image',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='image_char',
            field=models.CharField(default='', max_length=256),
        ),
    ]
