# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20151225_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='image_char',
        ),
    ]
