# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160114_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
