# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_examplemodel_image_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='image_char',
            field=models.CharField(default='', max_length=256),
        ),
    ]
