# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160121_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
