# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160121_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=256),
            preserve_default=False,
        ),
    ]
