# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20151226_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplemodel',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='model_pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='image_char',
            new_name='title',
        ),
        migrations.AlterModelTable(
            name='examplemodel',
            table='examplemodel',
        ),
    ]
