# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_examplemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='image',
        ),
    ]
