# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_examplemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='image',
            field=models.ImageField(default='media/fb.jpg', upload_to='media/'),
        ),
    ]
