# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
