# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160107_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
