# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20160108_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='/image/'),
        ),
    ]
