# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20160108_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
