# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20160111_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='firt_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='last_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='role',
            field=models.CharField(default='', max_length=256),
        ),
    ]
