# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20160112_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='firt_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='password',
        ),
        migrations.RemoveField(
            model_name='document',
            name='role',
        ),
    ]
