# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_document_firt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firt_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='firt_name',
        ),
    ]
