# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20160112_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Users'),
        ),
    ]
