# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20160112_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='users',
        ),
    ]
