# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20160112_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Users'),
        ),
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Document'),
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Users'),
        ),
    ]
